version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: beta
  ignore:
  - dependency-name: "@octokit/graphql"
    versions:
    - 4.5.8
    - 4.5.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: next
    versions:
    - 10.0.4
    - 10.0.6
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
